// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'sdk_api.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ClientHandlePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_NetworkProfilePasswordHandlePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PreparedNetworkProfilePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile;

  @protected
  ClientHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          dynamic raw);

  @protected
  NetworkProfilePasswordHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          dynamic raw);

  @protected
  PreparedNetworkProfile
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          dynamic raw);

  @protected
  ClientHandle
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          dynamic raw);

  @protected
  NetworkProfilePasswordHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          dynamic raw);

  @protected
  PreparedNetworkProfile
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          dynamic raw);

  @protected
  ClientHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          dynamic raw);

  @protected
  NetworkProfilePasswordHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          dynamic raw);

  @protected
  PreparedNetworkProfile
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AcademicStageDto dco_decode_academic_stage_dto(dynamic raw);

  @protected
  AcademicTermDto dco_decode_academic_term_dto(dynamic raw);

  @protected
  AccountStateDto dco_decode_account_state_dto(dynamic raw);

  @protected
  AccountStatusDto dco_decode_account_status_dto(dynamic raw);

  @protected
  ArticleDetailDto dco_decode_article_detail_dto(dynamic raw);

  @protected
  ArticleDetailResultDto dco_decode_article_detail_result_dto(dynamic raw);

  @protected
  AuthStatusDto dco_decode_auth_status_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  NetworkProfilePasswordHandle
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CampusCardInteractionDto dco_decode_box_autoadd_campus_card_interaction_dto(
      dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GradeReportKindDto dco_decode_box_autoadd_grade_report_kind_dto(dynamic raw);

  @protected
  IdentityLoginResultDto dco_decode_box_autoadd_identity_login_result_dto(
      dynamic raw);

  @protected
  LoginStageDto dco_decode_box_autoadd_login_stage_dto(dynamic raw);

  @protected
  OverviewScheduleDto dco_decode_box_autoadd_overview_schedule_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CacheFreshnessDto dco_decode_cache_freshness_dto(dynamic raw);

  @protected
  CampusCardAccountDto dco_decode_campus_card_account_dto(dynamic raw);

  @protected
  CampusCardAccountResultDto dco_decode_campus_card_account_result_dto(
      dynamic raw);

  @protected
  CampusCardInteractionDto dco_decode_campus_card_interaction_dto(dynamic raw);

  @protected
  CampusCardTransactionDto dco_decode_campus_card_transaction_dto(dynamic raw);

  @protected
  CampusCardTransactionTypeDto dco_decode_campus_card_transaction_type_dto(
      dynamic raw);

  @protected
  CampusCardTransactionsDto dco_decode_campus_card_transactions_dto(
      dynamic raw);

  @protected
  CampusCardTransactionsResultDto
      dco_decode_campus_card_transactions_result_dto(dynamic raw);

  @protected
  ClassroomAvailabilityDto dco_decode_classroom_availability_dto(dynamic raw);

  @protected
  ClassroomAvailabilityResultDto dco_decode_classroom_availability_result_dto(
      dynamic raw);

  @protected
  ClassroomBuildingDto dco_decode_classroom_building_dto(dynamic raw);

  @protected
  ClassroomBuildingsDto dco_decode_classroom_buildings_dto(dynamic raw);

  @protected
  ClassroomBuildingsResultDto dco_decode_classroom_buildings_result_dto(
      dynamic raw);

  @protected
  ClassroomRoomDto dco_decode_classroom_room_dto(dynamic raw);

  @protected
  ClassroomSlotDto dco_decode_classroom_slot_dto(dynamic raw);

  @protected
  ClassroomSlotStatusDto dco_decode_classroom_slot_status_dto(dynamic raw);

  @protected
  CourseGradeDto dco_decode_course_grade_dto(dynamic raw);

  @protected
  DailyOverviewDto dco_decode_daily_overview_dto(dynamic raw);

  @protected
  DailyOverviewResultDto dco_decode_daily_overview_result_dto(dynamic raw);

  @protected
  ElectricityPaymentHistoryDto dco_decode_electricity_payment_history_dto(
      dynamic raw);

  @protected
  ElectricityPaymentHistoryResultDto
      dco_decode_electricity_payment_history_result_dto(dynamic raw);

  @protected
  ElectricityPaymentRecordDto dco_decode_electricity_payment_record_dto(
      dynamic raw);

  @protected
  ElectricityRemainderDto dco_decode_electricity_remainder_dto(dynamic raw);

  @protected
  ElectricityRemainderResultDto dco_decode_electricity_remainder_result_dto(
      dynamic raw);

  @protected
  ExamDto dco_decode_exam_dto(dynamic raw);

  @protected
  ExamReportDto dco_decode_exam_report_dto(dynamic raw);

  @protected
  ExamReportResultDto dco_decode_exam_report_result_dto(dynamic raw);

  @protected
  ExamWeekdayDto dco_decode_exam_weekday_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GradeReportDto dco_decode_grade_report_dto(dynamic raw);

  @protected
  GradeReportKindDto dco_decode_grade_report_kind_dto(dynamic raw);

  @protected
  GradeReportResultDto dco_decode_grade_report_result_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IdentityLoginResultDto dco_decode_identity_login_result_dto(dynamic raw);

  @protected
  LearnAnnouncementDto dco_decode_learn_announcement_dto(dynamic raw);

  @protected
  LearnAnnouncementsDto dco_decode_learn_announcements_dto(dynamic raw);

  @protected
  LearnAnnouncementsResultDto dco_decode_learn_announcements_result_dto(
      dynamic raw);

  @protected
  LearnCourseCatalogDto dco_decode_learn_course_catalog_dto(dynamic raw);

  @protected
  LearnCourseCatalogResultDto dco_decode_learn_course_catalog_result_dto(
      dynamic raw);

  @protected
  LearnCourseDiscussionDto dco_decode_learn_course_discussion_dto(dynamic raw);

  @protected
  LearnCourseDiscussionsDto dco_decode_learn_course_discussions_dto(
      dynamic raw);

  @protected
  LearnCourseDiscussionsResultDto
      dco_decode_learn_course_discussions_result_dto(dynamic raw);

  @protected
  LearnCourseDto dco_decode_learn_course_dto(dynamic raw);

  @protected
  LearnCourseFileCategoriesDto dco_decode_learn_course_file_categories_dto(
      dynamic raw);

  @protected
  LearnCourseFileCategoriesResultDto
      dco_decode_learn_course_file_categories_result_dto(dynamic raw);

  @protected
  LearnCourseFileCategoryDto dco_decode_learn_course_file_category_dto(
      dynamic raw);

  @protected
  LearnCourseFileDto dco_decode_learn_course_file_dto(dynamic raw);

  @protected
  LearnCourseFilesDto dco_decode_learn_course_files_dto(dynamic raw);

  @protected
  LearnCourseFilesResultDto dco_decode_learn_course_files_result_dto(
      dynamic raw);

  @protected
  LearnHomeworkAttachmentDto dco_decode_learn_homework_attachment_dto(
      dynamic raw);

  @protected
  LearnHomeworkAttachmentKindDto dco_decode_learn_homework_attachment_kind_dto(
      dynamic raw);

  @protected
  LearnHomeworkDetailDto dco_decode_learn_homework_detail_dto(dynamic raw);

  @protected
  LearnHomeworkDetailResultDto dco_decode_learn_homework_detail_result_dto(
      dynamic raw);

  @protected
  LearnHomeworkDto dco_decode_learn_homework_dto(dynamic raw);

  @protected
  LearnHomeworkListDto dco_decode_learn_homework_list_dto(dynamic raw);

  @protected
  LearnHomeworkListResultDto dco_decode_learn_homework_list_result_dto(
      dynamic raw);

  @protected
  LearnHomeworkStateDto dco_decode_learn_homework_state_dto(dynamic raw);

  @protected
  LearnTermCalendarDto dco_decode_learn_term_calendar_dto(dynamic raw);

  @protected
  LearnTermCalendarResultDto dco_decode_learn_term_calendar_result_dto(
      dynamic raw);

  @protected
  LibraryAvailabilityDto dco_decode_library_availability_dto(dynamic raw);

  @protected
  LibraryAvailabilityResultDto dco_decode_library_availability_result_dto(
      dynamic raw);

  @protected
  LibraryDayDto dco_decode_library_day_dto(dynamic raw);

  @protected
  LibraryDirectoryDto dco_decode_library_directory_dto(dynamic raw);

  @protected
  LibraryDirectoryResultDto dco_decode_library_directory_result_dto(
      dynamic raw);

  @protected
  LibraryFloorDto dco_decode_library_floor_dto(dynamic raw);

  @protected
  LibraryFloorsDto dco_decode_library_floors_dto(dynamic raw);

  @protected
  LibraryFloorsResultDto dco_decode_library_floors_result_dto(dynamic raw);

  @protected
  LibraryPlaceDto dco_decode_library_place_dto(dynamic raw);

  @protected
  LibrarySeatDto dco_decode_library_seat_dto(dynamic raw);

  @protected
  LibrarySectionDto dco_decode_library_section_dto(dynamic raw);

  @protected
  LibrarySectionsDto dco_decode_library_sections_dto(dynamic raw);

  @protected
  LibrarySectionsResultDto dco_decode_library_sections_result_dto(dynamic raw);

  @protected
  LibrarySocketStateDto dco_decode_library_socket_state_dto(dynamic raw);

  @protected
  LibrarySocketStatusDto dco_decode_library_socket_status_dto(dynamic raw);

  @protected
  LibrarySocketsDto dco_decode_library_sockets_dto(dynamic raw);

  @protected
  LibrarySocketsResultDto dco_decode_library_sockets_result_dto(dynamic raw);

  @protected
  LibraryTimeWindowDto dco_decode_library_time_window_dto(dynamic raw);

  @protected
  LibraryTimeWindowsDto dco_decode_library_time_windows_dto(dynamic raw);

  @protected
  LibraryTimeWindowsResultDto dco_decode_library_time_windows_result_dto(
      dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AcademicTermDto> dco_decode_list_academic_term_dto(dynamic raw);

  @protected
  List<CampusCardTransactionDto> dco_decode_list_campus_card_transaction_dto(
      dynamic raw);

  @protected
  List<ClassroomBuildingDto> dco_decode_list_classroom_building_dto(
      dynamic raw);

  @protected
  List<ClassroomRoomDto> dco_decode_list_classroom_room_dto(dynamic raw);

  @protected
  List<ClassroomSlotDto> dco_decode_list_classroom_slot_dto(dynamic raw);

  @protected
  List<CourseGradeDto> dco_decode_list_course_grade_dto(dynamic raw);

  @protected
  List<ElectricityPaymentRecordDto>
      dco_decode_list_electricity_payment_record_dto(dynamic raw);

  @protected
  List<ExamDto> dco_decode_list_exam_dto(dynamic raw);

  @protected
  List<LearnAnnouncementDto> dco_decode_list_learn_announcement_dto(
      dynamic raw);

  @protected
  List<LearnCourseDiscussionDto> dco_decode_list_learn_course_discussion_dto(
      dynamic raw);

  @protected
  List<LearnCourseDto> dco_decode_list_learn_course_dto(dynamic raw);

  @protected
  List<LearnCourseFileCategoryDto>
      dco_decode_list_learn_course_file_category_dto(dynamic raw);

  @protected
  List<LearnCourseFileDto> dco_decode_list_learn_course_file_dto(dynamic raw);

  @protected
  List<LearnHomeworkAttachmentDto>
      dco_decode_list_learn_homework_attachment_dto(dynamic raw);

  @protected
  List<LearnHomeworkDto> dco_decode_list_learn_homework_dto(dynamic raw);

  @protected
  List<LibraryFloorDto> dco_decode_list_library_floor_dto(dynamic raw);

  @protected
  List<LibraryPlaceDto> dco_decode_list_library_place_dto(dynamic raw);

  @protected
  List<LibrarySeatDto> dco_decode_list_library_seat_dto(dynamic raw);

  @protected
  List<LibrarySectionDto> dco_decode_list_library_section_dto(dynamic raw);

  @protected
  List<LibrarySocketStatusDto> dco_decode_list_library_socket_status_dto(
      dynamic raw);

  @protected
  List<LibraryTimeWindowDto> dco_decode_list_library_time_window_dto(
      dynamic raw);

  @protected
  List<NetworkProfileDto> dco_decode_list_network_profile_dto(dynamic raw);

  @protected
  List<NewsArticleDto> dco_decode_list_news_article_dto(dynamic raw);

  @protected
  List<NewsAttachmentDto> dco_decode_list_news_attachment_dto(dynamic raw);

  @protected
  List<NewsChannelDto> dco_decode_list_news_channel_dto(dynamic raw);

  @protected
  List<NewsSourceDto> dco_decode_list_news_source_dto(dynamic raw);

  @protected
  List<NewsSubscriptionDto> dco_decode_list_news_subscription_dto(dynamic raw);

  @protected
  List<OverviewScheduleDto> dco_decode_list_overview_schedule_dto(dynamic raw);

  @protected
  List<OverviewTodoDto> dco_decode_list_overview_todo_dto(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ScheduleEventDto> dco_decode_list_schedule_event_dto(dynamic raw);

  @protected
  List<SelfServiceDeviceDto> dco_decode_list_self_service_device_dto(
      dynamic raw);

  @protected
  List<ServiceHallPhaseItemDto> dco_decode_list_service_hall_phase_item_dto(
      dynamic raw);

  @protected
  List<ServiceHallPhaseStepDto> dco_decode_list_service_hall_phase_step_dto(
      dynamic raw);

  @protected
  List<ServiceHallServiceDto> dco_decode_list_service_hall_service_dto(
      dynamic raw);

  @protected
  List<ServiceHallTaskDto> dco_decode_list_service_hall_task_dto(dynamic raw);

  @protected
  List<ServiceHallWorkflowTaskDto>
      dco_decode_list_service_hall_workflow_task_dto(dynamic raw);

  @protected
  LoginStageDto dco_decode_login_stage_dto(dynamic raw);

  @protected
  NetworkAccessMethodDto dco_decode_network_access_method_dto(dynamic raw);

  @protected
  NetworkProfileDto dco_decode_network_profile_dto(dynamic raw);

  @protected
  NetworkProfileFillDto dco_decode_network_profile_fill_dto(dynamic raw);

  @protected
  NewsArticleDto dco_decode_news_article_dto(dynamic raw);

  @protected
  NewsAttachmentDto dco_decode_news_attachment_dto(dynamic raw);

  @protected
  NewsCatalogCoverageDto dco_decode_news_catalog_coverage_dto(dynamic raw);

  @protected
  NewsCatalogDto dco_decode_news_catalog_dto(dynamic raw);

  @protected
  NewsCatalogResultDto dco_decode_news_catalog_result_dto(dynamic raw);

  @protected
  NewsChannelDto dco_decode_news_channel_dto(dynamic raw);

  @protected
  NewsFavoritesDto dco_decode_news_favorites_dto(dynamic raw);

  @protected
  NewsFavoritesResultDto dco_decode_news_favorites_result_dto(dynamic raw);

  @protected
  NewsPageDto dco_decode_news_page_dto(dynamic raw);

  @protected
  NewsPageResultDto dco_decode_news_page_result_dto(dynamic raw);

  @protected
  NewsSourceDto dco_decode_news_source_dto(dynamic raw);

  @protected
  NewsSubscriptionDto dco_decode_news_subscription_dto(dynamic raw);

  @protected
  NewsSubscriptionsDto dco_decode_news_subscriptions_dto(dynamic raw);

  @protected
  NewsSubscriptionsResultDto dco_decode_news_subscriptions_result_dto(
      dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  NetworkProfilePasswordHandle?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  CampusCardInteractionDto?
      dco_decode_opt_box_autoadd_campus_card_interaction_dto(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  GradeReportKindDto? dco_decode_opt_box_autoadd_grade_report_kind_dto(
      dynamic raw);

  @protected
  IdentityLoginResultDto? dco_decode_opt_box_autoadd_identity_login_result_dto(
      dynamic raw);

  @protected
  LoginStageDto? dco_decode_opt_box_autoadd_login_stage_dto(dynamic raw);

  @protected
  OverviewScheduleDto? dco_decode_opt_box_autoadd_overview_schedule_dto(
      dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  OverviewScheduleDto dco_decode_overview_schedule_dto(dynamic raw);

  @protected
  OverviewScheduleKindDto dco_decode_overview_schedule_kind_dto(dynamic raw);

  @protected
  OverviewSectionFailuresDto dco_decode_overview_section_failures_dto(
      dynamic raw);

  @protected
  OverviewTodoDto dco_decode_overview_todo_dto(dynamic raw);

  @protected
  PortalAddressRegistrationDto dco_decode_portal_address_registration_dto(
      dynamic raw);

  @protected
  PortalConnectionResultDto dco_decode_portal_connection_result_dto(
      dynamic raw);

  @protected
  PortalConnectionStateDto dco_decode_portal_connection_state_dto(dynamic raw);

  @protected
  PortalObservationDto dco_decode_portal_observation_dto(dynamic raw);

  @protected
  ReadCoverageDto dco_decode_read_coverage_dto(dynamic raw);

  @protected
  ReadMetadataDto dco_decode_read_metadata_dto(dynamic raw);

  @protected
  ReadPolicyDto dco_decode_read_policy_dto(dynamic raw);

  @protected
  ReadSourceDto dco_decode_read_source_dto(dynamic raw);

  @protected
  SavedLearnCourseFileDto dco_decode_saved_learn_course_file_dto(dynamic raw);

  @protected
  ScheduleEventDto dco_decode_schedule_event_dto(dynamic raw);

  @protected
  ScheduleEventKindDto dco_decode_schedule_event_kind_dto(dynamic raw);

  @protected
  SchoolCalendarImageDto dco_decode_school_calendar_image_dto(dynamic raw);

  @protected
  SchoolCalendarImageResultDto dco_decode_school_calendar_image_result_dto(
      dynamic raw);

  @protected
  SchoolCalendarLanguageDto dco_decode_school_calendar_language_dto(
      dynamic raw);

  @protected
  SchoolCalendarSemesterDto dco_decode_school_calendar_semester_dto(
      dynamic raw);

  @protected
  SdkErrorDto dco_decode_sdk_error_dto(dynamic raw);

  @protected
  SecondFactorMethodDto dco_decode_second_factor_method_dto(dynamic raw);

  @protected
  SelfServiceAccountDto dco_decode_self_service_account_dto(dynamic raw);

  @protected
  SelfServiceAccountResultDto dco_decode_self_service_account_result_dto(
      dynamic raw);

  @protected
  SelfServiceCaptchaDto dco_decode_self_service_captcha_dto(dynamic raw);

  @protected
  SelfServiceDeviceDto dco_decode_self_service_device_dto(dynamic raw);

  @protected
  SelfServiceDevicesResultDto dco_decode_self_service_devices_result_dto(
      dynamic raw);

  @protected
  SelfServiceLoginPhaseDto dco_decode_self_service_login_phase_dto(dynamic raw);

  @protected
  SelfServiceLoginResultDto dco_decode_self_service_login_result_dto(
      dynamic raw);

  @protected
  SelfServiceUsageDto dco_decode_self_service_usage_dto(dynamic raw);

  @protected
  SelfServiceUsageResultDto dco_decode_self_service_usage_result_dto(
      dynamic raw);

  @protected
  SemesterScheduleDto dco_decode_semester_schedule_dto(dynamic raw);

  @protected
  SemesterScheduleResultDto dco_decode_semester_schedule_result_dto(
      dynamic raw);

  @protected
  ServiceHallDirectoryDto dco_decode_service_hall_directory_dto(dynamic raw);

  @protected
  ServiceHallDirectoryResultDto dco_decode_service_hall_directory_result_dto(
      dynamic raw);

  @protected
  ServiceHallPendingDto dco_decode_service_hall_pending_dto(dynamic raw);

  @protected
  ServiceHallPendingResultDto dco_decode_service_hall_pending_result_dto(
      dynamic raw);

  @protected
  ServiceHallPhaseDetailsDto dco_decode_service_hall_phase_details_dto(
      dynamic raw);

  @protected
  ServiceHallPhaseDetailsResultDto
      dco_decode_service_hall_phase_details_result_dto(dynamic raw);

  @protected
  ServiceHallPhaseItemDto dco_decode_service_hall_phase_item_dto(dynamic raw);

  @protected
  ServiceHallPhaseStepDto dco_decode_service_hall_phase_step_dto(dynamic raw);

  @protected
  ServiceHallReadPolicyDto dco_decode_service_hall_read_policy_dto(dynamic raw);

  @protected
  ServiceHallServiceDto dco_decode_service_hall_service_dto(dynamic raw);

  @protected
  ServiceHallTaskDto dco_decode_service_hall_task_dto(dynamic raw);

  @protected
  ServiceHallTaskListDto dco_decode_service_hall_task_list_dto(dynamic raw);

  @protected
  ServiceHallTaskListResultDto dco_decode_service_hall_task_list_result_dto(
      dynamic raw);

  @protected
  ServiceHallTaskViewDto dco_decode_service_hall_task_view_dto(dynamic raw);

  @protected
  ServiceHallWorkflowTaskDto dco_decode_service_hall_workflow_task_dto(
      dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ClientHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          SseDeserializer deserializer);

  @protected
  NetworkProfilePasswordHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          SseDeserializer deserializer);

  @protected
  PreparedNetworkProfile
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          SseDeserializer deserializer);

  @protected
  ClientHandle
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          SseDeserializer deserializer);

  @protected
  NetworkProfilePasswordHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          SseDeserializer deserializer);

  @protected
  PreparedNetworkProfile
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          SseDeserializer deserializer);

  @protected
  ClientHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          SseDeserializer deserializer);

  @protected
  NetworkProfilePasswordHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          SseDeserializer deserializer);

  @protected
  PreparedNetworkProfile
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AcademicStageDto sse_decode_academic_stage_dto(SseDeserializer deserializer);

  @protected
  AcademicTermDto sse_decode_academic_term_dto(SseDeserializer deserializer);

  @protected
  AccountStateDto sse_decode_account_state_dto(SseDeserializer deserializer);

  @protected
  AccountStatusDto sse_decode_account_status_dto(SseDeserializer deserializer);

  @protected
  ArticleDetailDto sse_decode_article_detail_dto(SseDeserializer deserializer);

  @protected
  ArticleDetailResultDto sse_decode_article_detail_result_dto(
      SseDeserializer deserializer);

  @protected
  AuthStatusDto sse_decode_auth_status_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  NetworkProfilePasswordHandle
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CampusCardInteractionDto sse_decode_box_autoadd_campus_card_interaction_dto(
      SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GradeReportKindDto sse_decode_box_autoadd_grade_report_kind_dto(
      SseDeserializer deserializer);

  @protected
  IdentityLoginResultDto sse_decode_box_autoadd_identity_login_result_dto(
      SseDeserializer deserializer);

  @protected
  LoginStageDto sse_decode_box_autoadd_login_stage_dto(
      SseDeserializer deserializer);

  @protected
  OverviewScheduleDto sse_decode_box_autoadd_overview_schedule_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CacheFreshnessDto sse_decode_cache_freshness_dto(
      SseDeserializer deserializer);

  @protected
  CampusCardAccountDto sse_decode_campus_card_account_dto(
      SseDeserializer deserializer);

  @protected
  CampusCardAccountResultDto sse_decode_campus_card_account_result_dto(
      SseDeserializer deserializer);

  @protected
  CampusCardInteractionDto sse_decode_campus_card_interaction_dto(
      SseDeserializer deserializer);

  @protected
  CampusCardTransactionDto sse_decode_campus_card_transaction_dto(
      SseDeserializer deserializer);

  @protected
  CampusCardTransactionTypeDto sse_decode_campus_card_transaction_type_dto(
      SseDeserializer deserializer);

  @protected
  CampusCardTransactionsDto sse_decode_campus_card_transactions_dto(
      SseDeserializer deserializer);

  @protected
  CampusCardTransactionsResultDto
      sse_decode_campus_card_transactions_result_dto(
          SseDeserializer deserializer);

  @protected
  ClassroomAvailabilityDto sse_decode_classroom_availability_dto(
      SseDeserializer deserializer);

  @protected
  ClassroomAvailabilityResultDto sse_decode_classroom_availability_result_dto(
      SseDeserializer deserializer);

  @protected
  ClassroomBuildingDto sse_decode_classroom_building_dto(
      SseDeserializer deserializer);

  @protected
  ClassroomBuildingsDto sse_decode_classroom_buildings_dto(
      SseDeserializer deserializer);

  @protected
  ClassroomBuildingsResultDto sse_decode_classroom_buildings_result_dto(
      SseDeserializer deserializer);

  @protected
  ClassroomRoomDto sse_decode_classroom_room_dto(SseDeserializer deserializer);

  @protected
  ClassroomSlotDto sse_decode_classroom_slot_dto(SseDeserializer deserializer);

  @protected
  ClassroomSlotStatusDto sse_decode_classroom_slot_status_dto(
      SseDeserializer deserializer);

  @protected
  CourseGradeDto sse_decode_course_grade_dto(SseDeserializer deserializer);

  @protected
  DailyOverviewDto sse_decode_daily_overview_dto(SseDeserializer deserializer);

  @protected
  DailyOverviewResultDto sse_decode_daily_overview_result_dto(
      SseDeserializer deserializer);

  @protected
  ElectricityPaymentHistoryDto sse_decode_electricity_payment_history_dto(
      SseDeserializer deserializer);

  @protected
  ElectricityPaymentHistoryResultDto
      sse_decode_electricity_payment_history_result_dto(
          SseDeserializer deserializer);

  @protected
  ElectricityPaymentRecordDto sse_decode_electricity_payment_record_dto(
      SseDeserializer deserializer);

  @protected
  ElectricityRemainderDto sse_decode_electricity_remainder_dto(
      SseDeserializer deserializer);

  @protected
  ElectricityRemainderResultDto sse_decode_electricity_remainder_result_dto(
      SseDeserializer deserializer);

  @protected
  ExamDto sse_decode_exam_dto(SseDeserializer deserializer);

  @protected
  ExamReportDto sse_decode_exam_report_dto(SseDeserializer deserializer);

  @protected
  ExamReportResultDto sse_decode_exam_report_result_dto(
      SseDeserializer deserializer);

  @protected
  ExamWeekdayDto sse_decode_exam_weekday_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GradeReportDto sse_decode_grade_report_dto(SseDeserializer deserializer);

  @protected
  GradeReportKindDto sse_decode_grade_report_kind_dto(
      SseDeserializer deserializer);

  @protected
  GradeReportResultDto sse_decode_grade_report_result_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IdentityLoginResultDto sse_decode_identity_login_result_dto(
      SseDeserializer deserializer);

  @protected
  LearnAnnouncementDto sse_decode_learn_announcement_dto(
      SseDeserializer deserializer);

  @protected
  LearnAnnouncementsDto sse_decode_learn_announcements_dto(
      SseDeserializer deserializer);

  @protected
  LearnAnnouncementsResultDto sse_decode_learn_announcements_result_dto(
      SseDeserializer deserializer);

  @protected
  LearnCourseCatalogDto sse_decode_learn_course_catalog_dto(
      SseDeserializer deserializer);

  @protected
  LearnCourseCatalogResultDto sse_decode_learn_course_catalog_result_dto(
      SseDeserializer deserializer);

  @protected
  LearnCourseDiscussionDto sse_decode_learn_course_discussion_dto(
      SseDeserializer deserializer);

  @protected
  LearnCourseDiscussionsDto sse_decode_learn_course_discussions_dto(
      SseDeserializer deserializer);

  @protected
  LearnCourseDiscussionsResultDto
      sse_decode_learn_course_discussions_result_dto(
          SseDeserializer deserializer);

  @protected
  LearnCourseDto sse_decode_learn_course_dto(SseDeserializer deserializer);

  @protected
  LearnCourseFileCategoriesDto sse_decode_learn_course_file_categories_dto(
      SseDeserializer deserializer);

  @protected
  LearnCourseFileCategoriesResultDto
      sse_decode_learn_course_file_categories_result_dto(
          SseDeserializer deserializer);

  @protected
  LearnCourseFileCategoryDto sse_decode_learn_course_file_category_dto(
      SseDeserializer deserializer);

  @protected
  LearnCourseFileDto sse_decode_learn_course_file_dto(
      SseDeserializer deserializer);

  @protected
  LearnCourseFilesDto sse_decode_learn_course_files_dto(
      SseDeserializer deserializer);

  @protected
  LearnCourseFilesResultDto sse_decode_learn_course_files_result_dto(
      SseDeserializer deserializer);

  @protected
  LearnHomeworkAttachmentDto sse_decode_learn_homework_attachment_dto(
      SseDeserializer deserializer);

  @protected
  LearnHomeworkAttachmentKindDto sse_decode_learn_homework_attachment_kind_dto(
      SseDeserializer deserializer);

  @protected
  LearnHomeworkDetailDto sse_decode_learn_homework_detail_dto(
      SseDeserializer deserializer);

  @protected
  LearnHomeworkDetailResultDto sse_decode_learn_homework_detail_result_dto(
      SseDeserializer deserializer);

  @protected
  LearnHomeworkDto sse_decode_learn_homework_dto(SseDeserializer deserializer);

  @protected
  LearnHomeworkListDto sse_decode_learn_homework_list_dto(
      SseDeserializer deserializer);

  @protected
  LearnHomeworkListResultDto sse_decode_learn_homework_list_result_dto(
      SseDeserializer deserializer);

  @protected
  LearnHomeworkStateDto sse_decode_learn_homework_state_dto(
      SseDeserializer deserializer);

  @protected
  LearnTermCalendarDto sse_decode_learn_term_calendar_dto(
      SseDeserializer deserializer);

  @protected
  LearnTermCalendarResultDto sse_decode_learn_term_calendar_result_dto(
      SseDeserializer deserializer);

  @protected
  LibraryAvailabilityDto sse_decode_library_availability_dto(
      SseDeserializer deserializer);

  @protected
  LibraryAvailabilityResultDto sse_decode_library_availability_result_dto(
      SseDeserializer deserializer);

  @protected
  LibraryDayDto sse_decode_library_day_dto(SseDeserializer deserializer);

  @protected
  LibraryDirectoryDto sse_decode_library_directory_dto(
      SseDeserializer deserializer);

  @protected
  LibraryDirectoryResultDto sse_decode_library_directory_result_dto(
      SseDeserializer deserializer);

  @protected
  LibraryFloorDto sse_decode_library_floor_dto(SseDeserializer deserializer);

  @protected
  LibraryFloorsDto sse_decode_library_floors_dto(SseDeserializer deserializer);

  @protected
  LibraryFloorsResultDto sse_decode_library_floors_result_dto(
      SseDeserializer deserializer);

  @protected
  LibraryPlaceDto sse_decode_library_place_dto(SseDeserializer deserializer);

  @protected
  LibrarySeatDto sse_decode_library_seat_dto(SseDeserializer deserializer);

  @protected
  LibrarySectionDto sse_decode_library_section_dto(
      SseDeserializer deserializer);

  @protected
  LibrarySectionsDto sse_decode_library_sections_dto(
      SseDeserializer deserializer);

  @protected
  LibrarySectionsResultDto sse_decode_library_sections_result_dto(
      SseDeserializer deserializer);

  @protected
  LibrarySocketStateDto sse_decode_library_socket_state_dto(
      SseDeserializer deserializer);

  @protected
  LibrarySocketStatusDto sse_decode_library_socket_status_dto(
      SseDeserializer deserializer);

  @protected
  LibrarySocketsDto sse_decode_library_sockets_dto(
      SseDeserializer deserializer);

  @protected
  LibrarySocketsResultDto sse_decode_library_sockets_result_dto(
      SseDeserializer deserializer);

  @protected
  LibraryTimeWindowDto sse_decode_library_time_window_dto(
      SseDeserializer deserializer);

  @protected
  LibraryTimeWindowsDto sse_decode_library_time_windows_dto(
      SseDeserializer deserializer);

  @protected
  LibraryTimeWindowsResultDto sse_decode_library_time_windows_result_dto(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AcademicTermDto> sse_decode_list_academic_term_dto(
      SseDeserializer deserializer);

  @protected
  List<CampusCardTransactionDto> sse_decode_list_campus_card_transaction_dto(
      SseDeserializer deserializer);

  @protected
  List<ClassroomBuildingDto> sse_decode_list_classroom_building_dto(
      SseDeserializer deserializer);

  @protected
  List<ClassroomRoomDto> sse_decode_list_classroom_room_dto(
      SseDeserializer deserializer);

  @protected
  List<ClassroomSlotDto> sse_decode_list_classroom_slot_dto(
      SseDeserializer deserializer);

  @protected
  List<CourseGradeDto> sse_decode_list_course_grade_dto(
      SseDeserializer deserializer);

  @protected
  List<ElectricityPaymentRecordDto>
      sse_decode_list_electricity_payment_record_dto(
          SseDeserializer deserializer);

  @protected
  List<ExamDto> sse_decode_list_exam_dto(SseDeserializer deserializer);

  @protected
  List<LearnAnnouncementDto> sse_decode_list_learn_announcement_dto(
      SseDeserializer deserializer);

  @protected
  List<LearnCourseDiscussionDto> sse_decode_list_learn_course_discussion_dto(
      SseDeserializer deserializer);

  @protected
  List<LearnCourseDto> sse_decode_list_learn_course_dto(
      SseDeserializer deserializer);

  @protected
  List<LearnCourseFileCategoryDto>
      sse_decode_list_learn_course_file_category_dto(
          SseDeserializer deserializer);

  @protected
  List<LearnCourseFileDto> sse_decode_list_learn_course_file_dto(
      SseDeserializer deserializer);

  @protected
  List<LearnHomeworkAttachmentDto>
      sse_decode_list_learn_homework_attachment_dto(
          SseDeserializer deserializer);

  @protected
  List<LearnHomeworkDto> sse_decode_list_learn_homework_dto(
      SseDeserializer deserializer);

  @protected
  List<LibraryFloorDto> sse_decode_list_library_floor_dto(
      SseDeserializer deserializer);

  @protected
  List<LibraryPlaceDto> sse_decode_list_library_place_dto(
      SseDeserializer deserializer);

  @protected
  List<LibrarySeatDto> sse_decode_list_library_seat_dto(
      SseDeserializer deserializer);

  @protected
  List<LibrarySectionDto> sse_decode_list_library_section_dto(
      SseDeserializer deserializer);

  @protected
  List<LibrarySocketStatusDto> sse_decode_list_library_socket_status_dto(
      SseDeserializer deserializer);

  @protected
  List<LibraryTimeWindowDto> sse_decode_list_library_time_window_dto(
      SseDeserializer deserializer);

  @protected
  List<NetworkProfileDto> sse_decode_list_network_profile_dto(
      SseDeserializer deserializer);

  @protected
  List<NewsArticleDto> sse_decode_list_news_article_dto(
      SseDeserializer deserializer);

  @protected
  List<NewsAttachmentDto> sse_decode_list_news_attachment_dto(
      SseDeserializer deserializer);

  @protected
  List<NewsChannelDto> sse_decode_list_news_channel_dto(
      SseDeserializer deserializer);

  @protected
  List<NewsSourceDto> sse_decode_list_news_source_dto(
      SseDeserializer deserializer);

  @protected
  List<NewsSubscriptionDto> sse_decode_list_news_subscription_dto(
      SseDeserializer deserializer);

  @protected
  List<OverviewScheduleDto> sse_decode_list_overview_schedule_dto(
      SseDeserializer deserializer);

  @protected
  List<OverviewTodoDto> sse_decode_list_overview_todo_dto(
      SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ScheduleEventDto> sse_decode_list_schedule_event_dto(
      SseDeserializer deserializer);

  @protected
  List<SelfServiceDeviceDto> sse_decode_list_self_service_device_dto(
      SseDeserializer deserializer);

  @protected
  List<ServiceHallPhaseItemDto> sse_decode_list_service_hall_phase_item_dto(
      SseDeserializer deserializer);

  @protected
  List<ServiceHallPhaseStepDto> sse_decode_list_service_hall_phase_step_dto(
      SseDeserializer deserializer);

  @protected
  List<ServiceHallServiceDto> sse_decode_list_service_hall_service_dto(
      SseDeserializer deserializer);

  @protected
  List<ServiceHallTaskDto> sse_decode_list_service_hall_task_dto(
      SseDeserializer deserializer);

  @protected
  List<ServiceHallWorkflowTaskDto>
      sse_decode_list_service_hall_workflow_task_dto(
          SseDeserializer deserializer);

  @protected
  LoginStageDto sse_decode_login_stage_dto(SseDeserializer deserializer);

  @protected
  NetworkAccessMethodDto sse_decode_network_access_method_dto(
      SseDeserializer deserializer);

  @protected
  NetworkProfileDto sse_decode_network_profile_dto(
      SseDeserializer deserializer);

  @protected
  NetworkProfileFillDto sse_decode_network_profile_fill_dto(
      SseDeserializer deserializer);

  @protected
  NewsArticleDto sse_decode_news_article_dto(SseDeserializer deserializer);

  @protected
  NewsAttachmentDto sse_decode_news_attachment_dto(
      SseDeserializer deserializer);

  @protected
  NewsCatalogCoverageDto sse_decode_news_catalog_coverage_dto(
      SseDeserializer deserializer);

  @protected
  NewsCatalogDto sse_decode_news_catalog_dto(SseDeserializer deserializer);

  @protected
  NewsCatalogResultDto sse_decode_news_catalog_result_dto(
      SseDeserializer deserializer);

  @protected
  NewsChannelDto sse_decode_news_channel_dto(SseDeserializer deserializer);

  @protected
  NewsFavoritesDto sse_decode_news_favorites_dto(SseDeserializer deserializer);

  @protected
  NewsFavoritesResultDto sse_decode_news_favorites_result_dto(
      SseDeserializer deserializer);

  @protected
  NewsPageDto sse_decode_news_page_dto(SseDeserializer deserializer);

  @protected
  NewsPageResultDto sse_decode_news_page_result_dto(
      SseDeserializer deserializer);

  @protected
  NewsSourceDto sse_decode_news_source_dto(SseDeserializer deserializer);

  @protected
  NewsSubscriptionDto sse_decode_news_subscription_dto(
      SseDeserializer deserializer);

  @protected
  NewsSubscriptionsDto sse_decode_news_subscriptions_dto(
      SseDeserializer deserializer);

  @protected
  NewsSubscriptionsResultDto sse_decode_news_subscriptions_result_dto(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  NetworkProfilePasswordHandle?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CampusCardInteractionDto?
      sse_decode_opt_box_autoadd_campus_card_interaction_dto(
          SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GradeReportKindDto? sse_decode_opt_box_autoadd_grade_report_kind_dto(
      SseDeserializer deserializer);

  @protected
  IdentityLoginResultDto? sse_decode_opt_box_autoadd_identity_login_result_dto(
      SseDeserializer deserializer);

  @protected
  LoginStageDto? sse_decode_opt_box_autoadd_login_stage_dto(
      SseDeserializer deserializer);

  @protected
  OverviewScheduleDto? sse_decode_opt_box_autoadd_overview_schedule_dto(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  OverviewScheduleDto sse_decode_overview_schedule_dto(
      SseDeserializer deserializer);

  @protected
  OverviewScheduleKindDto sse_decode_overview_schedule_kind_dto(
      SseDeserializer deserializer);

  @protected
  OverviewSectionFailuresDto sse_decode_overview_section_failures_dto(
      SseDeserializer deserializer);

  @protected
  OverviewTodoDto sse_decode_overview_todo_dto(SseDeserializer deserializer);

  @protected
  PortalAddressRegistrationDto sse_decode_portal_address_registration_dto(
      SseDeserializer deserializer);

  @protected
  PortalConnectionResultDto sse_decode_portal_connection_result_dto(
      SseDeserializer deserializer);

  @protected
  PortalConnectionStateDto sse_decode_portal_connection_state_dto(
      SseDeserializer deserializer);

  @protected
  PortalObservationDto sse_decode_portal_observation_dto(
      SseDeserializer deserializer);

  @protected
  ReadCoverageDto sse_decode_read_coverage_dto(SseDeserializer deserializer);

  @protected
  ReadMetadataDto sse_decode_read_metadata_dto(SseDeserializer deserializer);

  @protected
  ReadPolicyDto sse_decode_read_policy_dto(SseDeserializer deserializer);

  @protected
  ReadSourceDto sse_decode_read_source_dto(SseDeserializer deserializer);

  @protected
  SavedLearnCourseFileDto sse_decode_saved_learn_course_file_dto(
      SseDeserializer deserializer);

  @protected
  ScheduleEventDto sse_decode_schedule_event_dto(SseDeserializer deserializer);

  @protected
  ScheduleEventKindDto sse_decode_schedule_event_kind_dto(
      SseDeserializer deserializer);

  @protected
  SchoolCalendarImageDto sse_decode_school_calendar_image_dto(
      SseDeserializer deserializer);

  @protected
  SchoolCalendarImageResultDto sse_decode_school_calendar_image_result_dto(
      SseDeserializer deserializer);

  @protected
  SchoolCalendarLanguageDto sse_decode_school_calendar_language_dto(
      SseDeserializer deserializer);

  @protected
  SchoolCalendarSemesterDto sse_decode_school_calendar_semester_dto(
      SseDeserializer deserializer);

  @protected
  SdkErrorDto sse_decode_sdk_error_dto(SseDeserializer deserializer);

  @protected
  SecondFactorMethodDto sse_decode_second_factor_method_dto(
      SseDeserializer deserializer);

  @protected
  SelfServiceAccountDto sse_decode_self_service_account_dto(
      SseDeserializer deserializer);

  @protected
  SelfServiceAccountResultDto sse_decode_self_service_account_result_dto(
      SseDeserializer deserializer);

  @protected
  SelfServiceCaptchaDto sse_decode_self_service_captcha_dto(
      SseDeserializer deserializer);

  @protected
  SelfServiceDeviceDto sse_decode_self_service_device_dto(
      SseDeserializer deserializer);

  @protected
  SelfServiceDevicesResultDto sse_decode_self_service_devices_result_dto(
      SseDeserializer deserializer);

  @protected
  SelfServiceLoginPhaseDto sse_decode_self_service_login_phase_dto(
      SseDeserializer deserializer);

  @protected
  SelfServiceLoginResultDto sse_decode_self_service_login_result_dto(
      SseDeserializer deserializer);

  @protected
  SelfServiceUsageDto sse_decode_self_service_usage_dto(
      SseDeserializer deserializer);

  @protected
  SelfServiceUsageResultDto sse_decode_self_service_usage_result_dto(
      SseDeserializer deserializer);

  @protected
  SemesterScheduleDto sse_decode_semester_schedule_dto(
      SseDeserializer deserializer);

  @protected
  SemesterScheduleResultDto sse_decode_semester_schedule_result_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallDirectoryDto sse_decode_service_hall_directory_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallDirectoryResultDto sse_decode_service_hall_directory_result_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallPendingDto sse_decode_service_hall_pending_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallPendingResultDto sse_decode_service_hall_pending_result_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallPhaseDetailsDto sse_decode_service_hall_phase_details_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallPhaseDetailsResultDto
      sse_decode_service_hall_phase_details_result_dto(
          SseDeserializer deserializer);

  @protected
  ServiceHallPhaseItemDto sse_decode_service_hall_phase_item_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallPhaseStepDto sse_decode_service_hall_phase_step_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallReadPolicyDto sse_decode_service_hall_read_policy_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallServiceDto sse_decode_service_hall_service_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallTaskDto sse_decode_service_hall_task_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallTaskListDto sse_decode_service_hall_task_list_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallTaskListResultDto sse_decode_service_hall_task_list_result_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallTaskViewDto sse_decode_service_hall_task_view_dto(
      SseDeserializer deserializer);

  @protected
  ServiceHallWorkflowTaskDto sse_decode_service_hall_workflow_task_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          ClientHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          NetworkProfilePasswordHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          PreparedNetworkProfile self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          ClientHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          NetworkProfilePasswordHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          PreparedNetworkProfile self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          ClientHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          NetworkProfilePasswordHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          PreparedNetworkProfile self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_academic_stage_dto(
      AcademicStageDto self, SseSerializer serializer);

  @protected
  void sse_encode_academic_term_dto(
      AcademicTermDto self, SseSerializer serializer);

  @protected
  void sse_encode_account_state_dto(
      AccountStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_account_status_dto(
      AccountStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_article_detail_dto(
      ArticleDetailDto self, SseSerializer serializer);

  @protected
  void sse_encode_article_detail_result_dto(
      ArticleDetailResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_auth_status_dto(AuthStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          NetworkProfilePasswordHandle self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_campus_card_interaction_dto(
      CampusCardInteractionDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_grade_report_kind_dto(
      GradeReportKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_identity_login_result_dto(
      IdentityLoginResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_login_stage_dto(
      LoginStageDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_overview_schedule_dto(
      OverviewScheduleDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_cache_freshness_dto(
      CacheFreshnessDto self, SseSerializer serializer);

  @protected
  void sse_encode_campus_card_account_dto(
      CampusCardAccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_campus_card_account_result_dto(
      CampusCardAccountResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_campus_card_interaction_dto(
      CampusCardInteractionDto self, SseSerializer serializer);

  @protected
  void sse_encode_campus_card_transaction_dto(
      CampusCardTransactionDto self, SseSerializer serializer);

  @protected
  void sse_encode_campus_card_transaction_type_dto(
      CampusCardTransactionTypeDto self, SseSerializer serializer);

  @protected
  void sse_encode_campus_card_transactions_dto(
      CampusCardTransactionsDto self, SseSerializer serializer);

  @protected
  void sse_encode_campus_card_transactions_result_dto(
      CampusCardTransactionsResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_classroom_availability_dto(
      ClassroomAvailabilityDto self, SseSerializer serializer);

  @protected
  void sse_encode_classroom_availability_result_dto(
      ClassroomAvailabilityResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_classroom_building_dto(
      ClassroomBuildingDto self, SseSerializer serializer);

  @protected
  void sse_encode_classroom_buildings_dto(
      ClassroomBuildingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_classroom_buildings_result_dto(
      ClassroomBuildingsResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_classroom_room_dto(
      ClassroomRoomDto self, SseSerializer serializer);

  @protected
  void sse_encode_classroom_slot_dto(
      ClassroomSlotDto self, SseSerializer serializer);

  @protected
  void sse_encode_classroom_slot_status_dto(
      ClassroomSlotStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_course_grade_dto(
      CourseGradeDto self, SseSerializer serializer);

  @protected
  void sse_encode_daily_overview_dto(
      DailyOverviewDto self, SseSerializer serializer);

  @protected
  void sse_encode_daily_overview_result_dto(
      DailyOverviewResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_electricity_payment_history_dto(
      ElectricityPaymentHistoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_electricity_payment_history_result_dto(
      ElectricityPaymentHistoryResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_electricity_payment_record_dto(
      ElectricityPaymentRecordDto self, SseSerializer serializer);

  @protected
  void sse_encode_electricity_remainder_dto(
      ElectricityRemainderDto self, SseSerializer serializer);

  @protected
  void sse_encode_electricity_remainder_result_dto(
      ElectricityRemainderResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_exam_dto(ExamDto self, SseSerializer serializer);

  @protected
  void sse_encode_exam_report_dto(ExamReportDto self, SseSerializer serializer);

  @protected
  void sse_encode_exam_report_result_dto(
      ExamReportResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_exam_weekday_dto(
      ExamWeekdayDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_grade_report_dto(
      GradeReportDto self, SseSerializer serializer);

  @protected
  void sse_encode_grade_report_kind_dto(
      GradeReportKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_grade_report_result_dto(
      GradeReportResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_identity_login_result_dto(
      IdentityLoginResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_announcement_dto(
      LearnAnnouncementDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_announcements_dto(
      LearnAnnouncementsDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_announcements_result_dto(
      LearnAnnouncementsResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_catalog_dto(
      LearnCourseCatalogDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_catalog_result_dto(
      LearnCourseCatalogResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_discussion_dto(
      LearnCourseDiscussionDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_discussions_dto(
      LearnCourseDiscussionsDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_discussions_result_dto(
      LearnCourseDiscussionsResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_dto(
      LearnCourseDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_file_categories_dto(
      LearnCourseFileCategoriesDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_file_categories_result_dto(
      LearnCourseFileCategoriesResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_file_category_dto(
      LearnCourseFileCategoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_file_dto(
      LearnCourseFileDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_files_dto(
      LearnCourseFilesDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_course_files_result_dto(
      LearnCourseFilesResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_homework_attachment_dto(
      LearnHomeworkAttachmentDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_homework_attachment_kind_dto(
      LearnHomeworkAttachmentKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_homework_detail_dto(
      LearnHomeworkDetailDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_homework_detail_result_dto(
      LearnHomeworkDetailResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_homework_dto(
      LearnHomeworkDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_homework_list_dto(
      LearnHomeworkListDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_homework_list_result_dto(
      LearnHomeworkListResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_homework_state_dto(
      LearnHomeworkStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_term_calendar_dto(
      LearnTermCalendarDto self, SseSerializer serializer);

  @protected
  void sse_encode_learn_term_calendar_result_dto(
      LearnTermCalendarResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_availability_dto(
      LibraryAvailabilityDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_availability_result_dto(
      LibraryAvailabilityResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_day_dto(LibraryDayDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_directory_dto(
      LibraryDirectoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_directory_result_dto(
      LibraryDirectoryResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_floor_dto(
      LibraryFloorDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_floors_dto(
      LibraryFloorsDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_floors_result_dto(
      LibraryFloorsResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_place_dto(
      LibraryPlaceDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_seat_dto(
      LibrarySeatDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_section_dto(
      LibrarySectionDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_sections_dto(
      LibrarySectionsDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_sections_result_dto(
      LibrarySectionsResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_socket_state_dto(
      LibrarySocketStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_socket_status_dto(
      LibrarySocketStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_sockets_dto(
      LibrarySocketsDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_sockets_result_dto(
      LibrarySocketsResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_time_window_dto(
      LibraryTimeWindowDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_time_windows_dto(
      LibraryTimeWindowsDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_time_windows_result_dto(
      LibraryTimeWindowsResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_academic_term_dto(
      List<AcademicTermDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_campus_card_transaction_dto(
      List<CampusCardTransactionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_classroom_building_dto(
      List<ClassroomBuildingDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_classroom_room_dto(
      List<ClassroomRoomDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_classroom_slot_dto(
      List<ClassroomSlotDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_course_grade_dto(
      List<CourseGradeDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_electricity_payment_record_dto(
      List<ElectricityPaymentRecordDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_exam_dto(List<ExamDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_learn_announcement_dto(
      List<LearnAnnouncementDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_learn_course_discussion_dto(
      List<LearnCourseDiscussionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_learn_course_dto(
      List<LearnCourseDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_learn_course_file_category_dto(
      List<LearnCourseFileCategoryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_learn_course_file_dto(
      List<LearnCourseFileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_learn_homework_attachment_dto(
      List<LearnHomeworkAttachmentDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_learn_homework_dto(
      List<LearnHomeworkDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library_floor_dto(
      List<LibraryFloorDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library_place_dto(
      List<LibraryPlaceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library_seat_dto(
      List<LibrarySeatDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library_section_dto(
      List<LibrarySectionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library_socket_status_dto(
      List<LibrarySocketStatusDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library_time_window_dto(
      List<LibraryTimeWindowDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_network_profile_dto(
      List<NetworkProfileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_news_article_dto(
      List<NewsArticleDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_news_attachment_dto(
      List<NewsAttachmentDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_news_channel_dto(
      List<NewsChannelDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_news_source_dto(
      List<NewsSourceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_news_subscription_dto(
      List<NewsSubscriptionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_overview_schedule_dto(
      List<OverviewScheduleDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_overview_todo_dto(
      List<OverviewTodoDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_schedule_event_dto(
      List<ScheduleEventDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_self_service_device_dto(
      List<SelfServiceDeviceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_service_hall_phase_item_dto(
      List<ServiceHallPhaseItemDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_service_hall_phase_step_dto(
      List<ServiceHallPhaseStepDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_service_hall_service_dto(
      List<ServiceHallServiceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_service_hall_task_dto(
      List<ServiceHallTaskDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_service_hall_workflow_task_dto(
      List<ServiceHallWorkflowTaskDto> self, SseSerializer serializer);

  @protected
  void sse_encode_login_stage_dto(LoginStageDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_access_method_dto(
      NetworkAccessMethodDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_profile_dto(
      NetworkProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_profile_fill_dto(
      NetworkProfileFillDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_article_dto(
      NewsArticleDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_attachment_dto(
      NewsAttachmentDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_catalog_coverage_dto(
      NewsCatalogCoverageDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_catalog_dto(
      NewsCatalogDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_catalog_result_dto(
      NewsCatalogResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_channel_dto(
      NewsChannelDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_favorites_dto(
      NewsFavoritesDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_favorites_result_dto(
      NewsFavoritesResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_page_dto(NewsPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_page_result_dto(
      NewsPageResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_source_dto(NewsSourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_subscription_dto(
      NewsSubscriptionDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_subscriptions_dto(
      NewsSubscriptionsDto self, SseSerializer serializer);

  @protected
  void sse_encode_news_subscriptions_result_dto(
      NewsSubscriptionsResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          NetworkProfilePasswordHandle? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_campus_card_interaction_dto(
      CampusCardInteractionDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_grade_report_kind_dto(
      GradeReportKindDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_identity_login_result_dto(
      IdentityLoginResultDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_login_stage_dto(
      LoginStageDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_overview_schedule_dto(
      OverviewScheduleDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_overview_schedule_dto(
      OverviewScheduleDto self, SseSerializer serializer);

  @protected
  void sse_encode_overview_schedule_kind_dto(
      OverviewScheduleKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_overview_section_failures_dto(
      OverviewSectionFailuresDto self, SseSerializer serializer);

  @protected
  void sse_encode_overview_todo_dto(
      OverviewTodoDto self, SseSerializer serializer);

  @protected
  void sse_encode_portal_address_registration_dto(
      PortalAddressRegistrationDto self, SseSerializer serializer);

  @protected
  void sse_encode_portal_connection_result_dto(
      PortalConnectionResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_portal_connection_state_dto(
      PortalConnectionStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_portal_observation_dto(
      PortalObservationDto self, SseSerializer serializer);

  @protected
  void sse_encode_read_coverage_dto(
      ReadCoverageDto self, SseSerializer serializer);

  @protected
  void sse_encode_read_metadata_dto(
      ReadMetadataDto self, SseSerializer serializer);

  @protected
  void sse_encode_read_policy_dto(ReadPolicyDto self, SseSerializer serializer);

  @protected
  void sse_encode_read_source_dto(ReadSourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_saved_learn_course_file_dto(
      SavedLearnCourseFileDto self, SseSerializer serializer);

  @protected
  void sse_encode_schedule_event_dto(
      ScheduleEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_schedule_event_kind_dto(
      ScheduleEventKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_school_calendar_image_dto(
      SchoolCalendarImageDto self, SseSerializer serializer);

  @protected
  void sse_encode_school_calendar_image_result_dto(
      SchoolCalendarImageResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_school_calendar_language_dto(
      SchoolCalendarLanguageDto self, SseSerializer serializer);

  @protected
  void sse_encode_school_calendar_semester_dto(
      SchoolCalendarSemesterDto self, SseSerializer serializer);

  @protected
  void sse_encode_sdk_error_dto(SdkErrorDto self, SseSerializer serializer);

  @protected
  void sse_encode_second_factor_method_dto(
      SecondFactorMethodDto self, SseSerializer serializer);

  @protected
  void sse_encode_self_service_account_dto(
      SelfServiceAccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_self_service_account_result_dto(
      SelfServiceAccountResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_self_service_captcha_dto(
      SelfServiceCaptchaDto self, SseSerializer serializer);

  @protected
  void sse_encode_self_service_device_dto(
      SelfServiceDeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_self_service_devices_result_dto(
      SelfServiceDevicesResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_self_service_login_phase_dto(
      SelfServiceLoginPhaseDto self, SseSerializer serializer);

  @protected
  void sse_encode_self_service_login_result_dto(
      SelfServiceLoginResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_self_service_usage_dto(
      SelfServiceUsageDto self, SseSerializer serializer);

  @protected
  void sse_encode_self_service_usage_result_dto(
      SelfServiceUsageResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_semester_schedule_dto(
      SemesterScheduleDto self, SseSerializer serializer);

  @protected
  void sse_encode_semester_schedule_result_dto(
      SemesterScheduleResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_directory_dto(
      ServiceHallDirectoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_directory_result_dto(
      ServiceHallDirectoryResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_pending_dto(
      ServiceHallPendingDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_pending_result_dto(
      ServiceHallPendingResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_phase_details_dto(
      ServiceHallPhaseDetailsDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_phase_details_result_dto(
      ServiceHallPhaseDetailsResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_phase_item_dto(
      ServiceHallPhaseItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_phase_step_dto(
      ServiceHallPhaseStepDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_read_policy_dto(
      ServiceHallReadPolicyDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_service_dto(
      ServiceHallServiceDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_task_dto(
      ServiceHallTaskDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_task_list_dto(
      ServiceHallTaskListDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_task_list_result_dto(
      ServiceHallTaskListResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_task_view_dto(
      ServiceHallTaskViewDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_hall_workflow_task_dto(
      ServiceHallWorkflowTaskDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientHandle(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkProfilePasswordHandle(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPreparedNetworkProfile(
          int ptr);
}
